// Complete Page Registry - 60+ pages for hash-based routing
// Task ID: infrastructure-pages

export interface PageRegistryItem {
  slug: string;
  title: string;
  breadcrumb: string[];
  metaDescription: string;
  bannerImage: string;
  sourceUrl: string;
  pageType: 'about' | 'why-tostem' | 'category' | 'design' | 'series' | 'experience' | 'tada' | 'knowledge' | 'contact';
}

export const pageRegistry: PageRegistryItem[] = [
  // About Tostem
  { slug: 'about-tostem', title: 'About Tostem', breadcrumb: ['Home', 'About Tostem'], metaDescription: 'Learn about Tostem India, a premium brand from LIXIL bringing Japanese innovation in aluminium windows and doors.', bannerImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/about-tostem/', pageType: 'about' },
  { slug: 'directors-message', title: "Leader's Message", breadcrumb: ['Home', 'About Tostem', "Leader's Message"], metaDescription: "Read the message from Tostem India's leadership about our vision and commitment to quality.", bannerImage: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/directors-message/', pageType: 'about' },
  { slug: 'our-purpose-and-behaviour', title: 'Our Purpose And Behaviour', breadcrumb: ['Home', 'About Tostem', 'Our Purpose And Behaviour'], metaDescription: "Discover Tostem India's purpose, values, and behaviours that drive our commitment to excellence.", bannerImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/our-purpose-and-behaviour', pageType: 'about' },
  { slug: 'lixil-window-system', title: 'LIXIL Window System', breadcrumb: ['Home', 'About Tostem', 'LIXIL Window System'], metaDescription: "Learn about LIXIL, Japan's largest building materials company and the parent of Tostem India.", bannerImage: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/lixil-window-system/', pageType: 'about' },
  { slug: 'awards', title: 'Awards', breadcrumb: ['Home', 'About Tostem', 'Awards'], metaDescription: 'Explore the awards and recognitions received by Tostem India for excellence in aluminium windows and doors.', bannerImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/awards', pageType: 'about' },

  // Why Tostem
  { slug: 'total-housing-solutions', title: 'Total Housing Solutions', breadcrumb: ['Home', 'Why Tostem', 'Total Housing Solutions'], metaDescription: "Discover Tostem's total housing solutions for complete home fenestration needs.", bannerImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/total-housing-solutions/', pageType: 'why-tostem' },
  { slug: 'japanese-innovation', title: 'Japanese Innovation', breadcrumb: ['Home', 'Why Tostem', 'Japanese Innovation'], metaDescription: 'Learn how Tostem brings Japanese innovation and monozukuri craftsmanship to Indian homes.', bannerImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/japanese-innovation/', pageType: 'why-tostem' },
  { slug: 'pre-engineered-system-windows', title: 'Pre Engineered System Windows', breadcrumb: ['Home', 'Why Tostem', 'Pre Engineered System Windows'], metaDescription: 'Understand what makes pre-engineered system windows superior to conventional on-site fabrication.', bannerImage: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/pre-engineered-system-windows/', pageType: 'why-tostem' },
  { slug: 'quality-assurance-and-services', title: 'Quality Assurance and Testing', breadcrumb: ['Home', 'Why Tostem', 'Quality Assurance and Testing'], metaDescription: "Learn about Tostem's rigorous quality assurance processes and 100+ quality checks per product.", bannerImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/quality-assurance-and-services/', pageType: 'why-tostem' },
  { slug: 'soundproof-window-door-performance', title: 'TOSTEM Product Performance', breadcrumb: ['Home', 'Why Tostem', 'Product Performance'], metaDescription: 'Explore Tostem product performance including soundproofing, thermal insulation, and water resistance ratings.', bannerImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/soundproof-window-door-performance', pageType: 'why-tostem' },
  { slug: 'anodized-aluminum-windows-surface-colour-protection', title: 'Surface & Colour Protection', breadcrumb: ['Home', 'Why Tostem', 'Surface & Colour Protection'], metaDescription: "Learn about Tostem's anodized aluminum finish that provides 5x harder surface and superior colour protection.", bannerImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/anodized-aluminum-windows-surface-colour-protection', pageType: 'why-tostem' },
  { slug: 'anodised-aluminium-windows-doors-colour', title: 'Anodised Aluminium Window & Door Colours', breadcrumb: ['Home', 'Why Tostem', 'Anodised Aluminium Colours'], metaDescription: 'Explore the range of anodised aluminium colours available for Tostem windows and doors.', bannerImage: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/anodised-aluminium-windows-doors-colour/', pageType: 'why-tostem' },
  { slug: 'soundproof-insulated-doors-and-windows', title: 'Sound Insulated Doors and Windows', breadcrumb: ['Home', 'Why Tostem', 'Sound Insulated Doors and Windows'], metaDescription: "Discover Tostem's sound insulated doors and windows that deliver up to 40dB noise reduction.", bannerImage: 'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/soundproof-insulated-doors-and-windows/', pageType: 'why-tostem' },

  // Product Category pages
  { slug: 'aluminium-doors-design-prices', title: 'Aluminium Doors', breadcrumb: ['Home', 'Our Product', 'Aluminium Doors'], metaDescription: "Explore Tostem's range of premium aluminium doors — sliding, casement, French, bi-fold, and more.", bannerImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/aluminium-doors-design-prices/', pageType: 'category' },
  { slug: 'aluminium-windows-design-prices', title: 'Aluminium Windows', breadcrumb: ['Home', 'Our Product', 'Aluminium Windows'], metaDescription: "Explore Tostem's range of premium aluminium windows — sliding, casement, awning, fixed, and more.", bannerImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/aluminium-windows-design-prices/', pageType: 'category' },
  { slug: 'steel-entrance-doors', title: 'Steel Entrance Doors', breadcrumb: ['Home', 'Our Product', 'Steel Entrance Doors'], metaDescription: "Discover Tostem's GIESTA steel entrance doors with Japanese design and superior security.", bannerImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/steel-entrance-doors/', pageType: 'category' },
  { slug: 'airflow-system', title: 'Airflow System', breadcrumb: ['Home', 'Our Product', 'Airflow System'], metaDescription: "Explore Tostem's airflow system solutions including ventilation doors, slots, and louvers.", bannerImage: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/airflow-system/', pageType: 'category' },
  { slug: 'facades', title: 'Facades', breadcrumb: ['Home', 'Our Product', 'Facades'], metaDescription: "Explore Tostem's facade solutions including curtain wall and storefront facades for commercial buildings.", bannerImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/facades/', pageType: 'category' },
  { slug: 'interior', title: 'Interior', breadcrumb: ['Home', 'Our Product', 'Interior'], metaDescription: "Explore Tostem's interior solutions including hanging doors, swing doors, and fixed dividers.", bannerImage: 'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/interior/', pageType: 'category' },

  // Design pages - Doors
  { slug: 'aluminium-sliding-doors', title: 'Aluminium Sliding Doors', breadcrumb: ['Home', 'Our Product', 'Aluminium Doors', 'Sliding Doors'], metaDescription: "Explore Tostem's premium aluminium sliding doors with smooth gliding and multi-track options.", bannerImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/aluminium-sliding-doors/', pageType: 'design' },
  { slug: 'aluminium-casement-doors', title: 'Aluminium Casement Doors', breadcrumb: ['Home', 'Our Product', 'Aluminium Doors', 'Casement Doors'], metaDescription: "Explore Tostem's aluminium casement doors with elegant swing-style design.", bannerImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/aluminium-casement-doors/', pageType: 'design' },
  { slug: 'aluminium-french-doors', title: 'Aluminium French Doors', breadcrumb: ['Home', 'Our Product', 'Aluminium Doors', 'French Doors'], metaDescription: "Explore Tostem's aluminium French doors with classic double-door design.", bannerImage: 'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/aluminium-french-doors/', pageType: 'design' },
  { slug: 'aluminium-bi-folding-doors', title: 'Aluminium Folding (Bi Fold) Doors', breadcrumb: ['Home', 'Our Product', 'Aluminium Doors', 'Bi Fold Doors'], metaDescription: "Explore Tostem's aluminium bi-fold doors that create wide-open spaces.", bannerImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/aluminium-bi-folding-doors/', pageType: 'design' },
  { slug: 'aluminium-corner-slider-door', title: 'Aluminium Corner Slider Door', breadcrumb: ['Home', 'Our Product', 'Aluminium Doors', 'Corner Slider'], metaDescription: "Explore Tostem's innovative corner slider doors for seamless indoor-outdoor transitions.", bannerImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/aluminium-corner-slider-door/', pageType: 'design' },
  { slug: 'aluminium-slide-fold-doors', title: 'Aluminium Slide and Fold Doors', breadcrumb: ['Home', 'Our Product', 'Aluminium Doors', 'Slide and Fold'], metaDescription: "Explore Tostem's aluminium slide and fold doors.", bannerImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/aluminium-slide-fold-doors/', pageType: 'design' },
  { slug: 'ventilation-doors', title: 'Ventilation Doors', breadcrumb: ['Home', 'Our Product', 'Airflow System', 'Ventilation Doors'], metaDescription: "Explore Tostem's ventilation doors with integrated airflow features.", bannerImage: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/ventilation-doors/', pageType: 'design' },

  // Design pages - Windows
  { slug: 'aluminium-sliding-windows-designs', title: 'Aluminium Sliding Windows', breadcrumb: ['Home', 'Our Product', 'Aluminium Windows', 'Sliding Windows'], metaDescription: "Explore Tostem's aluminium sliding windows with effortless operation.", bannerImage: 'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/aluminium-sliding-windows-designs/', pageType: 'design' },
  { slug: 'aluminium-casement-windows', title: 'Aluminium Casement Windows', breadcrumb: ['Home', 'Our Product', 'Aluminium Windows', 'Casement Windows'], metaDescription: "Explore Tostem's aluminium casement windows for maximum ventilation.", bannerImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/aluminium-casement-windows/', pageType: 'design' },
  { slug: 'aluminium-hung-awning-windows', title: 'Aluminium Awning Windows', breadcrumb: ['Home', 'Our Product', 'Aluminium Windows', 'Awning Windows'], metaDescription: "Explore Tostem's aluminium awning windows for excellent ventilation with weather protection.", bannerImage: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/aluminium-hung-awning-windows/', pageType: 'design' },
  { slug: 'aluminium-fixed-window', title: 'Aluminium Fixed Window', breadcrumb: ['Home', 'Our Product', 'Aluminium Windows', 'Fixed Windows'], metaDescription: "Explore Tostem's aluminium fixed windows for maximised natural light and panoramic views.", bannerImage: 'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/aluminium-fixed-window/', pageType: 'design' },
  { slug: 'aluminium-glass-to-glass-corner-window', title: 'Aluminium Glass To Glass Corner Windows', breadcrumb: ['Home', 'Our Product', 'Aluminium Windows', 'Glass To Glass Corner'], metaDescription: "Explore Tostem's stunning glass-to-glass corner windows for uninterrupted panoramic views.", bannerImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/aluminium-glass-to-glass-corner-window/', pageType: 'design' },
  { slug: 'aluminium-french-windows', title: 'Aluminium French Windows', breadcrumb: ['Home', 'Our Product', 'Aluminium Windows', 'French Windows'], metaDescription: "Explore Tostem's aluminium French windows combining elegance with durability.", bannerImage: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/aluminium-french-windows/', pageType: 'design' },
  { slug: 'aluminium-tilt-slide-windows', title: 'Aluminium Tilt and Slide Windows', breadcrumb: ['Home', 'Our Product', 'Aluminium Windows', 'Tilt and Slide'], metaDescription: "Explore Tostem's dual-function tilt and slide windows.", bannerImage: 'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/aluminium-tilt-slide-windows/', pageType: 'design' },
  { slug: 'aluminium-slit-windows', title: 'Aluminium Slit Windows', breadcrumb: ['Home', 'Our Product', 'Aluminium Windows', 'Slit Windows'], metaDescription: "Explore Tostem's narrow profile slit windows for modern architectural designs.", bannerImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/aluminium-slit-windows/', pageType: 'design' },
  { slug: 'aluminium-vertical-sliding-windows', title: 'Aluminium Vertical Sliding Windows', breadcrumb: ['Home', 'Our Product', 'Aluminium Windows', 'Vertical Sliding'], metaDescription: "Explore Tostem's aluminium vertical sliding windows.", bannerImage: 'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/aluminium-vertical-sliding-windows/', pageType: 'design' },

  // Series pages
  { slug: 'giesta-doors', title: 'Giesta Doors', breadcrumb: ['Home', 'Our Product', 'Steel Entrance Doors', 'Giesta Doors'], metaDescription: "Explore Tostem's GIESTA doors with Japanese design and superior security features.", bannerImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/giesta-doors/', pageType: 'series' },
  { slug: 'giesta-ventilation-doors', title: 'Giesta with Ventilation', breadcrumb: ['Home', 'Our Product', 'Steel Entrance Doors', 'Giesta Ventilation'], metaDescription: "Explore Tostem's GIESTA doors with built-in ventilation features.", bannerImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/giesta-ventilation-doors/', pageType: 'series' },
  { slug: 'ventilation-slots', title: 'Ventilation Slot', breadcrumb: ['Home', 'Our Product', 'Airflow System', 'Ventilation Slot'], metaDescription: "Explore Tostem's ventilation slots for controlled airflow.", bannerImage: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/ventilation-slots/', pageType: 'design' },
  { slug: 'aluminum-louver', title: 'Aluminium Louvers', breadcrumb: ['Home', 'Our Product', 'Airflow System', 'Aluminium Louvers'], metaDescription: "Explore Tostem's aluminium louvers for architectural ventilation solutions.", bannerImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/aluminum-louver/', pageType: 'design' },
  { slug: 'glass-louver', title: 'Glass Louvers', breadcrumb: ['Home', 'Our Product', 'Airflow System', 'Glass Louvers'], metaDescription: "Explore Tostem's glass louvers for elegant ventilation solutions.", bannerImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/glass-louver/', pageType: 'design' },
  { slug: 'facade-curtain-wall', title: 'Curtain Wall Facades', breadcrumb: ['Home', 'Our Product', 'Facades', 'Curtain Wall'], metaDescription: "Explore Tostem's curtain wall facade systems for commercial buildings.", bannerImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/facade-curtain-wall/', pageType: 'design' },
  { slug: 'facade-store-front', title: 'Store Front Facades', breadcrumb: ['Home', 'Our Product', 'Facades', 'Store Front'], metaDescription: "Explore Tostem's storefront facade systems for retail and office buildings.", bannerImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/facade-store-front/', pageType: 'design' },
  { slug: 'hanging-door', title: 'Hanging Doors', breadcrumb: ['Home', 'Our Product', 'Interior', 'Hanging Doors'], metaDescription: "Explore Tostem's aluminium hanging doors for modern interior spaces.", bannerImage: 'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/hanging-door/', pageType: 'design' },
  { slug: 'swing-door', title: 'Swing Doors', breadcrumb: ['Home', 'Our Product', 'Interior', 'Swing Doors'], metaDescription: "Explore Tostem's aluminium swing doors for interior applications.", bannerImage: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/swing-door/', pageType: 'design' },
  { slug: 'fixed-divider', title: 'Fixed Divider', breadcrumb: ['Home', 'Our Product', 'Interior', 'Fixed Divider'], metaDescription: "Explore Tostem's fixed dividers for elegant room partition solutions.", bannerImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/fixed-divider/', pageType: 'design' },
  { slug: 'grants-windows-doors-series', title: 'Grants Series', breadcrumb: ['Home', 'Our Product', 'Grants Series'], metaDescription: 'Explore the versatile GRANTS series from Tostem offering elegant aluminium windows and doors.', bannerImage: 'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/grants-windows-doors-series/', pageType: 'series' },
  { slug: 'atis-windows-doors-series', title: 'ATIS Series', breadcrumb: ['Home', 'Our Product', 'ATIS Series'], metaDescription: 'Explore the premium ATIS series from Tostem offering top-tier thermal insulation and soundproofing.', bannerImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/atis-windows-doors-series/', pageType: 'series' },
  { slug: 'we-plus-windows-doors-series', title: 'We Plus Series', breadcrumb: ['Home', 'Our Product', 'We Plus Series'], metaDescription: 'Explore the next-generation WE+ series from Tostem with enhanced energy efficiency.', bannerImage: 'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/we-plus-windows-doors-series/', pageType: 'series' },
  { slug: 'we-70-windows-doors-series', title: 'We 70 Series', breadcrumb: ['Home', 'Our Product', 'We 70 Series'], metaDescription: 'Explore the balanced WE-70 series from Tostem offering quality at a great value.', bannerImage: 'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/we-70-windows-doors-series/', pageType: 'series' },

  // Experience pages
  { slug: 'e-catalogue', title: 'E-catalogue', breadcrumb: ['Home', 'Driving Experience', 'E-catalogue'], metaDescription: "Browse Tostem's e-catalogue for our complete range of aluminium windows and doors.", bannerImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/e-catalogue/', pageType: 'experience' },
  { slug: 'modern-window-door-design', title: 'Modern Window & Door Design', breadcrumb: ['Home', 'Driving Experience', 'Modern Design'], metaDescription: 'Explore modern window and door design ideas from Tostem.', bannerImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/modern-window-door-design/', pageType: 'experience' },
  { slug: 'gallery', title: 'Gallery', breadcrumb: ['Home', 'Driving Experience', 'Gallery'], metaDescription: "Browse Tostem's project gallery showcasing residential and commercial installations.", bannerImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/gallery/', pageType: 'experience' },

  // TADA pages
  { slug: 'tada-2025', title: 'TADA-2025', breadcrumb: ['Home', 'TADA', 'TADA-2025'], metaDescription: 'View the TADA 2025 award winners and nominations.', bannerImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/tada-category/tada-2025/', pageType: 'tada' },
  { slug: 'tada-2024', title: 'TADA-2024', breadcrumb: ['Home', 'TADA', 'TADA-2024'], metaDescription: 'View the TADA 2024 award winners.', bannerImage: 'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/tada-category/tada-2024/', pageType: 'tada' },
  { slug: 'tada-2023', title: 'TADA-2023', breadcrumb: ['Home', 'TADA', 'TADA-2023'], metaDescription: 'View the TADA 2023 award winners.', bannerImage: 'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/tada-category/tada-2023/', pageType: 'tada' },

  // Knowledge pages
  { slug: 'what-is-pre-engineered-system-window', title: 'What is Pre Engineered System Window', breadcrumb: ['Home', 'Knowledge Experience', 'Pre Engineered System Windows'], metaDescription: 'Learn what a pre-engineered system window is and how it differs from conventional windows.', bannerImage: 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/what-is-pre-engineered-system-window/', pageType: 'knowledge' },
  { slug: 'planning-a-system-window', title: 'Planning a System Window', breadcrumb: ['Home', 'Knowledge Experience', 'Planning a System Window'], metaDescription: 'Guide on planning and selecting the right system window for your home.', bannerImage: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/planning-a-system-window/', pageType: 'knowledge' },
  { slug: 'system-aluminum-windows', title: 'System Aluminum Windows', breadcrumb: ['Home', 'Knowledge Experience', 'System Aluminum Windows'], metaDescription: 'Learn about system aluminum windows and their advantages over conventional alternatives.', bannerImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/system-aluminum-windows/', pageType: 'knowledge' },
  { slug: 'blog', title: 'Blog', breadcrumb: ['Home', 'Knowledge Experience', 'Blog'], metaDescription: 'Read expert insights, guides, and the latest trends in aluminium windows and doors.', bannerImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/blog/', pageType: 'knowledge' },
  { slug: 'glossary', title: 'Glossary', breadcrumb: ['Home', 'Knowledge Experience', 'Glossary'], metaDescription: 'A-Z glossary of window and door terminology.', bannerImage: 'https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/glossary/', pageType: 'knowledge' },
  { slug: 'testimonials', title: 'Testimonials', breadcrumb: ['Home', 'Knowledge Experience', 'Testimonials'], metaDescription: 'Read what architects, builders, and homeowners say about Tostem.', bannerImage: 'https://images.unsplash.com/photo-1600210492493-0946911123ea?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/testimonials/', pageType: 'knowledge' },

  // Contact page
  { slug: 'contact', title: 'Contact Us', breadcrumb: ['Home', 'Reach Us', 'Contact'], metaDescription: 'Get in touch with Tostem India. Find our offices, studios, and contact information.', bannerImage: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1920&q=80', sourceUrl: 'https://www.tostemindia.com/contact/', pageType: 'contact' },
];

// Helper: get page by slug
export function getPageBySlug(slug: string): PageRegistryItem | undefined {
  return pageRegistry.find(p => p.slug === slug);
}

// Helper: get pages by type
export function getPagesByType(pageType: PageRegistryItem['pageType']): PageRegistryItem[] {
  return pageRegistry.filter(p => p.pageType === pageType);
}
